insert into diagnoses (id, name, category_id) values (1,'heart', 1);
insert into diagnoses (id, name, category_id) values (2,'stuff', 1);
insert into diagnoses (id, name, category_id) values (3,'heart things', 1);
insert into diagnoses (id, name, category_id) values (4,'things', 1);
insert into diagnoses (id, name, category_id) values (5,'another heart', 1);
insert into diagnoses (id, name, category_id) values (6,'Im stuff', 1);
insert into diagnoses (id, name, category_id) values (7,'more heart things', 1);
insert into diagnoses (id, name, category_id) values (8,'more things', 1);
insert into diagnoses (id, name, category_id) values (9,'yet another heart', 1);
insert into diagnoses (id, name, category_id) values (10,'joes stuff', 1);
insert into diagnoses (id, name, category_id) values (11,'even more heart things', 1);
insert into diagnoses (id, name, category_id) values (12,'im things', 1);
insert into diagnoses (id, name, category_id) values (13,'thing 13', 1);
insert into diagnoses (id, name, category_id) values (14,'thing 14', 1);
insert into diagnoses (id, name, category_id) values (15,'thing 15', 1);
insert into diagnoses (id, name, category_id) values (16,'thing 16', 1);
insert into diagnoses (id, name, category_id) values (17,'thing 17', 1);
insert into diagnoses (id, name, category_id) values (18,'thing 18', 1);
insert into diagnoses (id, name, category_id) values (19,'thing 19', 1);
insert into diagnoses (id, name, category_id) values (20,'thing 20', 1);

insert into cases (id, name, demographics, notes) values (1,'things that went wront', '80 y/o woman', null);
insert into cases (id, name, demographics, notes) values (2,'things from kid', '6 y/o kid', 'the kid was nice');
insert into cases (id, name, demographics, notes) values (3,'dog title', '8 y/o dog', null);

insert into cases_diagnoses_link (case_id, diagnosis_id) values (1,2);
insert into cases_diagnoses_link (case_id, diagnosis_id) values (1,1);
insert into cases_diagnoses_link (case_id, diagnosis_id) values (1,3);
insert into cases_diagnoses_link (case_id, diagnosis_id) values (2,2);
insert into cases_diagnoses_link (case_id, diagnosis_id) values (3,2);
insert into cases_diagnoses_link (case_id, diagnosis_id) values (3,1);