-- MySQL Script generated by MySQL Workbench
-- Wed Jan  1 20:31:52 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema medicaldb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `medicaldb` ;

-- -----------------------------------------------------
-- Schema medicaldb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `medicaldb` ;
USE `medicaldb` ;

-- -----------------------------------------------------
-- Table `medicaldb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `medicaldb`.`users` ;

CREATE TABLE IF NOT EXISTS `medicaldb`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `medicaldb`.`cases`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `medicaldb`.`cases` ;

CREATE TABLE IF NOT EXISTS `medicaldb`.`cases` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `demographics` VARCHAR(100) NOT NULL,
  `ward` VARCHAR(100) NULL DEFAULT NULL,
  `presenting_complaint` VARCHAR(100) NULL DEFAULT NULL,
  `presenting_complaint_history` VARCHAR(100) NULL DEFAULT NULL,
  `medical_history` VARCHAR(100) NULL DEFAULT NULL,
  `drug_history` VARCHAR(100) NULL DEFAULT NULL,
  `allergies` VARCHAR(100) NULL DEFAULT NULL,
  `family_history` VARCHAR(100) NULL DEFAULT NULL,
  `social_history` VARCHAR(100) NULL DEFAULT NULL,
  `notes` VARCHAR(300) NULL DEFAULT NULL,
  `date_created` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_cases_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `medicaldb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `medicaldb`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `medicaldb`.`categories` ;

CREATE TABLE IF NOT EXISTS `medicaldb`.`categories` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_categories_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `medicaldb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `medicaldb`.`diagnoses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `medicaldb`.`diagnoses` ;

CREATE TABLE IF NOT EXISTS `medicaldb`.`diagnoses` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED  NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `category_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_diagnoses_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `medicaldb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_diagnoses_categories`
    FOREIGN KEY (`category_id`)
    REFERENCES `medicaldb`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `medicaldb`.`cases_diagnoses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `medicaldb`.`cases_diagnoses_link` ;

CREATE TABLE IF NOT EXISTS `medicaldb`.`cases_diagnoses_link` (
  `diagnosis_id` INT UNSIGNED NOT NULL,
  `case_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`diagnosis_id`, `case_id`),
  CONSTRAINT `fk_cases_diagnoses_link_diagnoses`
    FOREIGN KEY (`diagnosis_id`)
    REFERENCES `medicaldb`.`diagnoses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cases_diagnoses_link_cases`
    FOREIGN KEY (`case_id`)
    REFERENCES `medicaldb`.`cases` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `medicaldb`.`diagnosis_informations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `medicaldb`.`diagnosis_informations` ;

CREATE TABLE IF NOT EXISTS `medicaldb`.`diagnosis_informations` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `diagnosis_id` INT UNSIGNED NOT NULL,
  `field` VARCHAR(100) NOT NULL,
  `value` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_diagnosis_information_diagnoses`
    FOREIGN KEY (`diagnosis_id`)
    REFERENCES `medicaldb`.`diagnoses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `medicaldb`.`freehand_notes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `medicaldb`.`freehand_notes` ;

CREATE TABLE IF NOT EXISTS `medicaldb`.`freehand_notes` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `diagnosis_id` INT UNSIGNED NOT NULL,
  `field` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_freehand_notes_diagnoses`
    FOREIGN KEY (`diagnosis_id`)
    REFERENCES `medicaldb`.`diagnoses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `medicaldb`.`notifications`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `medicaldb`.`notifications` ;

CREATE TABLE IF NOT EXISTS `medicaldb`.`notifications` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `diagnosis_id` INT UNSIGNED NOT NULL,
  `content` VARCHAR(100) NULL DEFAULT NULL,
  `creation_date` DATETIME NULL DEFAULT NULL,
  `is_read` TINYINT(1) NULL DEFAULT NULL,
  `is_done` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_notifications_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `medicaldb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `medicaldb`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `medicaldb`.`roles` ;

CREATE TABLE IF NOT EXISTS `medicaldb`.`roles` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `medicaldb`.`users_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `medicaldb`.`users_roles_link` ;

CREATE TABLE IF NOT EXISTS `medicaldb`.`users_roles_link` (
  `user_id` INT UNSIGNED NOT NULL,
  `role_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`user_id`, `role_id`),
  CONSTRAINT `fk_user_roles_role`
    FOREIGN KEY (`role_id`)
    REFERENCES `medicaldb`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_roles_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `medicaldb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `medicaldb`.`wards`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `medicaldb`.`wards` ;

CREATE TABLE IF NOT EXISTS `medicaldb`.`wards` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_ward_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `medicaldb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `medicaldb`.`ward_cases_link`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `medicaldb`.`ward_cases_link` ;

CREATE TABLE IF NOT EXISTS `medicaldb`.`ward_cases_link` (
  `ward_id` INT UNSIGNED NOT NULL,
  `case_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ward_id`, `case_id`),
  CONSTRAINT `fk_ward_cases_link_ward`
    FOREIGN KEY (`ward_id`)
    REFERENCES `medicaldb`.`wards` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ward_cases_link_cases`
    FOREIGN KEY (`case_id`)
    REFERENCES `medicaldb`.`cases` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
